# list a room ID where users can control the bot.
# you may need to set autojoin to on temporarily to get your bot to accept the invite if this
# is a private room
controlroom:

# the base command alias -- this is useful to change if you have multiple bots in the same
# channel that use this plugin (and only_DM is turned off)
command: admin
